apiVersion: v1
kind: ConfigMap
metadata:
  name: hotels-database-config
  namespace: hotels
data:
  POSTGRES_DB: dbname
  POSTGRES_USER: dbuser
---
apiVersion: v1
kind: Secret
metadata:
  name: hotels-database-secret
  namespace: hotels
type: Opaque
data:
  POSTGRES_PASSWORD: ZGJwYXNz
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hotels-database-pvc
  namespace: hotels
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hotels-database
  namespace: hotels
spec:
  serviceName: hotels-database-service
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:13
        env:
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: hotels-database-config
                key: POSTGRES_DB
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: hotels-database-config
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: hotels-database-secret
                key: POSTGRES_PASSWORD
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: hotels-database-data
          mountPath: /var/lib/postgresql/data
      volumes:
        - name: hotels-database-data
          persistentVolumeClaim:
            claimName: hotels-database-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: hotels-database-service
  namespace: hotels
spec:
  selector:
    app: postgresql 
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432



