# Generated by Django 5.0.6 on 2024-06-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotelsapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="image",
            field=models.CharField(max_length=255),
        ),
    ]
